version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/e2e-app"
      - "/TestProject"
      - "/"
    open-pull-requests-limit: 0 # install only security updates
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test(deps):"
    allow:
      - dependency-type: "all"
    groups:
      test-deps:
        patterns:
          - "*"
        applies-to: security-updates

  - package-ecosystem: "npm"
    directory: sdk
    open-pull-requests-limit: 0 # install only security updates
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: scope
    allow:
      - dependency-type: "all"
    groups:
      dev-deps:
        dependency-type: "development"
        applies-to: security-updates
