name: Analyze Commit Messages
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write
jobs:
  analyze-commits:
    name: Generate docs and coverage report
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/analyze-commits.yml@v1
    with:
      prepareCommand: |
        sudo gem install -n /usr/local/bin cocoapods
        pod --version
      semanticReleasePlugins: |
        @fingerprintjs/semantic-release-native-dependency-plugin@^1.2.1
      releaseWorkingDirectory: ./sdk
