name: E2E Tests

on:
  pull_request:
  release:
    types:
      - published

jobs:
  e2e-tests-android:
    runs-on: ubuntu-latest
    name: Android E2E Tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 22.x

      - uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: 17

      - run: yarn install

      - run: yarn build
        if: github.event_name != 'release'

      - name: Install dependencies in e2e-app
        run: yarn install
        working-directory: e2e-app

      - name: Install ${{github.event.release.tag_name}} version of the package
        run: yarn install @fingerprintjs/fingerprintjs-pro-react-native@${{github.event.release.tag_name}}
        if: github.event_name == 'release'
        working-directory: e2e-app

      - name: Get device name
        id: device
        run: node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT
        working-directory: e2e-app

      - run: npx detox build --configuration android.emu.release
        working-directory: e2e-app

      - name: Detox test
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d
        with:
          api-level: 35
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          script: cd e2e-app && npx detox test --configuration android.emu.release --headless --record-logs all

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: e2e-app/artifacts
