# Local fork of the fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1 workflow
# to accommodate for yarn usage.
# TODO: Remove at some point after this repo is migrated to pnpm.
name: 'Release SDK using changesets'
on:
  workflow_call:
    inputs:
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string
      github-release-files:
        description: A comma-delimited list of glob patterns to identify the local files to attach to the GitHub release.
        type: string
        required: false
        default: ''
      version-command:
        description: 'Command to run for project versioning'
        default: yarn exec changeset version
        type: string
      publish-command:
        description: 'Command to run for project publishing'
        default: yarn exec changeset publish
        type: string
      language:
        description: 'Programming language for the project. Supported values are "java", "dotnet", "python", "golang", "flutter" and "php".'
        required: true
        type: string
      language-version:
        description: 'Version of the programming language to setup.'
        required: true
        type: string
      java-version:
        description: 'Version of Java to setup.'
        required: false
        type: string
        default: '11'
      appId:
        type: string
        required: true
        description: 'GitHub app id for release process.'
      runnerAppId:
        type: string
        default: ''
        required: false
        description: 'GitHub app id for creating PR.'
      useTrustedPublishing:
        type: boolean
        required: false
        default: false
        description: 'Whether to use trusted publishing for publishing packages'
    secrets:
      APP_PRIVATE_KEY:
        description: 'GitHub App private key to request GitHub token for release process.'
        required: true
      RUNNER_APP_PRIVATE_KEY:
        description: 'GitHub App private key to request GitHub token for creating PR.'
        required: false
      NPM_AUTH_TOKEN:
        description: 'NPM authentication token for publishing packages.'
        required: false

jobs:
  determine-changesets-step:
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.changeset-determine-step.outputs.action }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.language-version }}
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile

      - name: 'Install changesets'
        run: 'yarn global add @changesets/cli'

      - name: Determine changesets step
        id: changeset-determine-step
        uses: fingerprintjs/dx-team-toolkit/.github/actions/changeset-determine-step@v1
  create-pr:
    runs-on: ubuntu-latest
    needs: determine-changesets-step
    if: needs.determine-changesets-step.outputs.action == 'pr' && inputs.runnerAppId != ''
    steps:
      - name: 'Get token for the GitHub App'
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.runnerAppId }}
          private-key: ${{ secrets.RUNNER_APP_PRIVATE_KEY }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      # Setup Node for other projects than node to install changeset globally via yarn
      - name: 'Setup Node'
        if: ${{ inputs.language != 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.language-version }}
          cache: 'yarn'

      - name: 'Install dependencies'
        if: ${{ inputs.language != 'node' }}
        run: yarn install --frozen-lockfile

      - name: 'Install changesets'
        run: 'yarn global add @changesets/cli'

      - name: Create Release PR
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          version: ${{ inputs.version-command }}
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  release:
    runs-on: ubuntu-latest
    environment: production
    needs: determine-changesets-step
    if: needs.determine-changesets-step.outputs.action == 'publish' || inputs.runnerAppId == ''
    steps:
      - name: 'Get token for the GitHub App'
        if: ${{ inputs.appId != '' }}
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      # Setup Node for other projects than node to install changeset globally via yarn
      - name: 'Setup Node'
        if: ${{ inputs.language != 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.language-version }}
          cache: 'yarn'

      - name: 'Install dependencies'
        if: ${{ inputs.language != 'node' }}
        run: yarn install --frozen-lockfile

      # Ensure npm 11.5.1 or later is installed for trusted publishing
      - name: Update npm
        if: ${{ inputs.useTrustedPublishing }}
        run: npm i -g npm@^11.5.1 && npm --version

      - name: 'Install changesets'
        run: 'yarn global add @changesets/cli'

      - name: Create Release
        id: changesets-release
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          publish: ${{ inputs.publish-command }}
          version: ${{ inputs.version-command }}
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          # If useTrustedPublishing is true, use OIDC for npm authentication instead of NPM_TOKEN https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868 by passing an empty string
          NPM_TOKEN: ${{ inputs.useTrustedPublishing && '' || secrets.NPM_AUTH_TOKEN }}

      - name: 'Upload files to GitHub release'
        if: inputs.github-release-files != '' && steps.changesets-release.outputs.published == 'true'
        env:
          PACKAGES: ${{ steps.changesets-release.outputs.publishedPackages }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Expand support for '**'
          shopt -s globstar

          # Convert no match patterns into the empty string to result in upload failures
          shopt -s nullglob

          # Calculate the tag name for the release of the primary package
          PACKAGE_NAME=$(jq -r .name ./package.json)
          VERSION=$(echo "$PACKAGES" | jq --arg package_name "$PACKAGE_NAME" -r '.[] | select(.name == $package_name) | .version')
          if [ "$(echo "$PACKAGES" | jq 'length')" -eq 1 ]; then
            TAG="v$VERSION"
          else
            # Changesets uses a different naming convention for multi-package repos
            TAG="${PACKAGE_NAME}@${VERSION}"
          fi

          IFS=',' read -ra GLOB_PATTERNS <<< "${{ inputs.github-release-files }}"
          for pattern in "${GLOB_PATTERNS[@]}"; do
            echo "Uploading files matching the pattern \"$pattern\" to the $TAG release"
            gh release upload "$TAG" $pattern
          done
