name: Test React Native Library

on:
  push:

env:
  XCODE_VERSION: 26.3

jobs:
  android-build-TestProject:
    name: Android TestProject - Build and Test React Native Library
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dependencies in TestProject
        run: pnpm install --frozen-lockfile
        working-directory: TestProject

      - name: Build Android
        working-directory: TestProject/android
        run: ./gradlew assembleDebug

      - name: Start Metro Bundler # and Test App
        working-directory: TestProject
        run: |
          pnpm start &
          sleep 10 # Allow Metro Bundler to start

  ios-build-TestProject:
    name: iOS TestProject - Build and Test React Native Library
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dependencies in TestProject
        run: pnpm install --frozen-lockfile
        working-directory: TestProject

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 #v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Install Pods
        working-directory: TestProject/ios
        run: pod install

      - name: Build iOS
        working-directory: TestProject/ios
        env:
          CI: true
        run: xcodebuild -workspace TestProject.xcworkspace -scheme TestProject -sdk iphonesimulator -configuration Debug build

      - name: Start Metro Bundler # and Test App
        working-directory: TestProject
        run: |
          pnpm start &
          sleep 10 # Allow Metro Bundler to start
